---
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: quay.io/debezium/kafka:3.0
    ports:
      - "9092:9092"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  database:
    image: quay.io/debezium/example-mysql:3.0
    ports:
      - "13306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER:          mysqluser
      MYSQL_PASSWORD:      mysqlpw 
  debezium:
    image: quay.io/debezium/connect:3.0
    ports:
      - "8083:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1 
      - CONFIG_STORAGE_TOPIC=my_connect_configs 
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
  

  db:
    image: postgres:17.4
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: pg_pass
    volumes:
      - ./pg.config:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
